---
title: "Bashing code"
date: 2022-08-28
---

theme: minima
author: RicardoUValencia
email: RUV61109@hotmail.com
description: # > this means to ignore newlines until "baseurl:"
  Welcome to my personal blog. We will learn about many technologies and the impact they are having through news from industry experts.

# social links
twitter_username: ru_viper # DO NOT include the @ character, or else the build will fail!
github_username:  RicardoUValencia # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
